(()=>{
const D=window.RUINAS_DATA,$=(q,r=document)=>r.querySelector(q),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),S=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const AP={'Jokara Amaréa':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22],'Nestira Amaréa':[1,2,3,4,5,7,8,9,13,14,15,16,17,18,19,20,21,22,23,24],Marv:[4,12,13,14,15,16,17,18,19,20,21,22,23,24],Loutes:[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24],Efepar:[1,2,3,5,7,8,9],'Mirel Amaréa':[1,2,3,4,5,7,8,9],Sersi:[2,3,7,8,13,14],Yndra:[4,5,6,8],Yoral:[1,2,4,9,21],Yrséa:[1,3,4,5],'Professor Talver':[4,5,8,9],Platisa:[3,15,16,17,18,19,20],Liri:[6,7,9,18],Malthar:[8,9,13,14,16,17,18,19,20,21],Gabasteres:[12,13,14,15,16,17,18,19,20,21,22,23]};
const REL=[['Jokara Amaréa','Nestira Amaréa','Irmãs: Peso e Sopro'],['Jokara Amaréa','Loutes','Proteção e mistério'],['Jokara Amaréa','Efepar','Amizade e apoio'],['Nestira Amaréa','Marv','Legado e continuidade'],['Malthar','Gabasteres','Ordem e domínio'],['Jokara Amaréa','Gabasteres','Resistência moral'],['Yoral','Jokara Amaréa','Pai e legado'],['Platisa','Jokara Amaréa','Conhecimento e humanidade']];
const EV=[[1,'As primeiras pedras'],[2,'O Primeiro Voo falha'],[3,'Loutes recebe um nome'],[4,'A profecia de Yndra'],[6,'O livro na caverna'],[7,'A denúncia pública'],[9,'O Cataclisma'],[10,'O primeiro fogo'],[15,'A chegada de Platisa'],[17,'O nome Polar'],[20,'As ruínas revelam a origem'],[22,'O sacrifício de Jokara'],[23,'A última perseguição'],[24,'O Vale']];
const MYS=[['loutes','Quem é Loutes?','Aberto','Uma criança deslocada, ligada ao ciclo e ao tempo; a origem permanece sem explicação.'],['ilhas-baixas','As Ilhas Baixas existiam?','Resolvido','Não. Eram uma mentira institucional usada para ocultar a morte dos exilados.'],['eterea','Por que Etérea caiu?','Parcial','Há sinais físicos e leitura simbólica pelo Peso, mas não uma resposta totalmente fechada.'],['ruinas','Quem construiu as ruínas?','Parcial','Povos da superfície ligados aos ancestrais eterí.'],['sopro','O Sopro é divino ou natural?','Aberto','A narrativa preserva as duas interpretações.']];
const LORE={fauna:[['Nuari',8],['Aranita',2],['Fera',5],['Criatura de escamas negras',2],['Ave branca',1],['Criatura segmentada',1]],flora:[['Selnara',3],['Flor-da-névoa',2],['Seda-das-alturas',2],['Musgos florais',2],['Folha colossal',1],['Raízes vivas',7]],alimentos:[['Carne de nuari',3],['Selnara seca',2],['Mel de flor-aérea',2],['Raízes cozidas',2],['Frutas da superfície',3],['Peixe de riacho',4]],conceitos:[['Sopro',12],['Peso',13],['Primeiro Voo',5],['Círculo do Peso',3],['Verbo da Corrente',2],['Ilhas Baixas',4]]};
const NAV=[['Visão geral',[['inicio','Início'],['capitulos','Capítulos']]],['Pessoas',[['personagens','Personagens'],['relacoes','Relações'],['familias','Famílias'],['organizacoes','Organizações']]],['História',[['acontecimentos','Acontecimentos'],['linha','Linha do tempo'],['consequencias','Causa e consequência'],['misterios','Mistérios']]],['Mundo',[['mapa','Mapa'],['lugares','Lugares']]],['Lore',[['fauna','Fauna'],['flora','Flora'],['alimentos','Alimentos'],['conceitos','Conceitos e leis']]],['Planejamento',[['continuidade','Continuidade'],['canon','Regras canônicas'],['decisoes','Decisões do autor']]]];
const charFiles={'Jokara Amaréa':'jokara','Nestira Amaréa':'nestira','Mirel Amaréa':'mirel-amarea'};
const charImage=name=>`assets/characters/ruinas/${charFiles[name]||S(name)}.webp`;
const placeImage=name=>`assets/places/ruinas/${S(name)}.webp`;
const initials=name=>String(name).split(' ').map(x=>x[0]).filter(Boolean).slice(0,2).join('');
const media=(src,alt,fallback,cls='')=>`<div class="${cls}"><img src="${E(src)}" alt="${E(alt)}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><b class="media-fallback" hidden>${E(fallback)}</b></div>`;
const st={route:'',tab:'geral',q:'',sort:'alpha',unused:false},H=(k,t,s='',x='')=>`<div class="head"><div><p class="eyebrow">${E(k)}</p><h1>${E(t)}</h1><p>${E(s)}</p></div>${x}</div>`,go=r=>location.hash='#/'+r,find=(a,id)=>a.find(x=>S(x.n)===id||x.n===id),err=()=>'<div class="empty"><h2>Página não encontrada</h2></div>';
function nav(){const b=st.route.split('/')[0];$('#nav').innerHTML=NAV.map(([g,a])=>`<div class="group"><span>${g}</span>${a.map(([r,l])=>`<button class="navb ${b===r?'active':''}" data-go="${r}">${l}</button>`).join('')}</div>`).join('');$('#crumb').textContent='Ruínas dos Céus · '+(NAV.flatMap(x=>x[1]).find(x=>x[0]===b)?.[1]||'Arquivo')}
window.RS={D,$,E,S,AP,REL,EV,MYS,LORE,NAV,st,H,go,find,err,nav,charImage,placeImage,initials,media};
})();