(()=>{
  'use strict';
  const R=window.RS,{D,E,H}=R,P=R.pages;
  const items=()=>D.common?.entities?.themes||[];
  const find=(collection,id)=>D.common?.findById?.(collection,id);
  const related=(route,title,sub='')=>`<button class="card mini-related-card" data-go="${E(route)}"><strong>${E(title)}</strong>${sub?`<small>${E(sub)}</small>`:''}</button>`;
  const list=(title,values)=>values?.length?`<section class="panel theme-stage14-block"><h2>${E(title)}</h2><ul>${values.map(value=>`<li>${R.linkify(value)}</li>`).join('')}</ul></section>`:'';
  P.temas=()=>H('Leitura temática','Temas','Ideias que atravessam a Queda e mudam de significado ao longo do livro.')+`<section class="theme-stage14-grid">${items().map(item=>`<article class="panel theme-stage14-card click" data-go="tema/${E(item.slug)}" tabindex="0" role="link"><p class="eyebrow">${E(item.category||'Tema')}</p><h2>${E(item.name)}</h2><p>${E(item.summary)}</p><div class="theme-stage14-counts"><span>${(item.chapterIds||[]).length} capítulos</span><span>${(item.characterIds||[]).length} personagens</span><span>${(item.symbols||[]).length} símbolos</span></div><p class="theme-question">${E(item.question||'')}</p><span class="theme-open">Aprofundar tema →</span></article>`).join('')}</section>`;
  P.tema=id=>{
    const item=items().find(x=>x.slug===id||x.id===id);if(!item)return R.err();
    const chars=(item.characterIds||[]).map(id=>find('characters',id)).filter(Boolean);
    const places=(item.placeIds||[]).map(id=>find('places',id)).filter(Boolean);
    const chapters=(item.chapterIds||[]).map(id=>find('chapters',id)).filter(Boolean);
    const events=(item.eventIds||[]).map(id=>find('timeline',id)).filter(Boolean);
    const evolution=(item.evolution||[]).map(step=>`<article class="theme-stage14-step"><small>${E(step.phase)}</small><div><h3>${E(step.title)}</h3><p>${R.linkify(step.text)}</p>${step.chapterIds?.length?`<div class="tags">${step.chapterIds.map(id=>find('chapters',id)).filter(Boolean).map(ch=>`<button class="tag" data-go="capitulo/${ch.number}">Cap. ${ch.number}</button>`).join('')}</div>`:''}</div></article>`).join('');
    return `<button class="back" data-go="temas">← Voltar</button>${H(item.category||'Tema',item.name,item.summary)}<article class="panel theme-stage14-block"><p class="theme-stage14-question">${E(item.question)}</p><p>${R.linkify(item.description)}</p></article><section class="theme-stage14-detail"><div class="theme-stage14-main">${list('Desenvolvimento',item.development)}${item.symbols?.length?`<section class="panel theme-stage14-block"><h2>Símbolos</h2><div class="theme-stage14-symbols">${item.symbols.map(symbol=>`<article class="theme-stage14-symbol"><strong>${E(symbol.name)}</strong><span>${R.linkify(symbol.meaning)}</span></article>`).join('')}</div></section>`:''}${evolution?`<section class="panel theme-stage14-block"><h2>Evolução ao longo do livro</h2><div class="theme-stage14-evolution">${evolution}</div></section>`:''}${item.interpretationNote?`<aside class="theme-stage14-note"><strong>Limite de interpretação:</strong> ${E(item.interpretationNote)}</aside>`:''}</div><aside class="theme-stage14-context"><section class="panel theme-stage14-context-card"><h2>Personagens</h2><div class="theme-related-list">${chars.length?chars.map(c=>related(`personagem/${c.slug}`,c.name,c.alias||c.importance||'')).join(''):'<p class="empty-inline">Nenhuma personagem ligada.</p>'}</div></section><section class="panel theme-stage14-context-card"><h2>Lugares</h2><div class="theme-related-list">${places.length?places.map(p=>related(`lugar/${p.slug}`,p.name,p.type||p.region||'Lugar')).join(''):'<p class="empty-inline">Nenhum lugar ligado.</p>'}</div></section><section class="panel theme-stage14-context-card"><h2>Capítulos</h2><div class="theme-related-list">${chapters.length?chapters.map(ch=>related(`capitulo/${ch.number}`,`Capítulo ${ch.number}`,ch.title)).join(''):'<p class="empty-inline">Nenhum capítulo ligado.</p>'}</div></section><section class="panel theme-stage14-context-card"><h2>Acontecimentos</h2><div class="theme-event-list">${events.length?events.map(event=>`<button class="card" data-go="linha/${E(event.slug)}">${E(event.name)}</button>`).join(''):'<p class="empty-inline">Nenhum acontecimento ligado.</p>'}</div></section></aside></section>`;
  };
})();
