(() => {
  'use strict';
  let page=null,cards=[],visible=[],active=0,lastFocus=null,currentFilter='all',query='',touchStartX=null;
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  function ensureLightbox(){
    let box=$('#diGalleryLightbox');if(box)return box;
    box=document.createElement('div');box.id='diGalleryLightbox';box.className='di-gallery-lightbox';box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-hidden','true');box.setAttribute('aria-label','Visualizador de galeria');
    box.innerHTML='<div class="di-gallery-lightbox-top"><div class="di-gallery-lightbox-title"><strong data-gallery-title></strong><small data-gallery-type></small></div><span class="di-gallery-lightbox-count" data-gallery-count></span><button class="di-gallery-close" type="button" data-gallery-close aria-label="Fechar">×</button></div><div class="di-gallery-lightbox-stage"><button class="di-gallery-nav di-gallery-prev" type="button" data-gallery-prev aria-label="Imagem anterior">‹</button><img data-gallery-image alt=""><button class="di-gallery-nav di-gallery-next" type="button" data-gallery-next aria-label="Próxima imagem">›</button></div><div class="di-gallery-lightbox-footer"><div class="di-gallery-caption" data-gallery-caption></div><button class="di-gallery-open-record" type="button" data-gallery-open-record hidden>Abrir ficha →</button></div>';
    document.body.appendChild(box);
    box.addEventListener('click',e=>{if(e.target===box||e.target.closest('[data-gallery-close]'))close();else if(e.target.closest('[data-gallery-prev]'))move(-1);else if(e.target.closest('[data-gallery-next]'))move(1);else if(e.target.closest('[data-gallery-open-record]'))openRecord();});
    const stage=$('.di-gallery-lightbox-stage',box);stage.addEventListener('touchstart',e=>{touchStartX=e.changedTouches[0]?.clientX??null},{passive:true});stage.addEventListener('touchend',e=>{if(touchStartX===null)return;const dx=(e.changedTouches[0]?.clientX??touchStartX)-touchStartX;touchStartX=null;if(Math.abs(dx)>48)move(dx<0?1:-1)},{passive:true});
    return box;
  }
  function itemFromCard(card){return{src:card.dataset.gallerySrc,title:card.dataset.galleryTitle,type:card.dataset.galleryType,caption:card.dataset.galleryCaption||card.dataset.galleryTitle,route:card.dataset.galleryRoute||'',card};}
  function normalise(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
  function matches(card){const category=currentFilter==='all'||card.dataset.galleryCategory===currentFilter;const haystack=normalise(`${card.dataset.galleryTitle} ${card.dataset.galleryType} ${card.dataset.galleryCaption}`);return category&&(!query||haystack.includes(normalise(query)))&&card.dataset.galleryBroken!=='true';}
  function refreshVisible(){visible=cards.filter(card=>!card.hidden&&card.dataset.galleryBroken!=='true').map(itemFromCard);const count=$('[data-gallery-visible-count]',page);if(count)count.textContent=`${visible.length} ${visible.length===1?'imagem':'imagens'}`;const empty=$('[data-gallery-empty]',page);if(empty)empty.hidden=visible.length>0;}
  function refreshFilterAvailability(){if(!page)return;$$('[data-gallery-filter]',page).forEach(btn=>{const filter=btn.dataset.galleryFilter;const available=filter==='all'?cards.some(card=>card.dataset.galleryBroken!=='true'):cards.some(card=>card.dataset.galleryCategory===filter&&card.dataset.galleryBroken!=='true');btn.hidden=!available;});}
  function applyFilters(){cards.forEach(card=>{card.hidden=!matches(card);card.setAttribute('aria-hidden',card.hidden?'true':'false');});$$('[data-gallery-filter]',page).forEach(btn=>{const selected=btn.dataset.galleryFilter===currentFilter;btn.classList.toggle('active',selected);btn.setAttribute('aria-pressed',String(selected));});refreshVisible();}
  function applyFilter(filter){currentFilter=filter||'all';applyFilters();}
  function markBroken(card){if(!card||card.dataset.galleryBroken==='true')return;card.dataset.galleryBroken='true';card.hidden=true;card.setAttribute('aria-hidden','true');refreshFilterAvailability();applyFilters();}
  function preload(index){if(visible.length<2)return;[-1,1].forEach(delta=>{const item=visible[(index+delta+visible.length)%visible.length];if(item){const img=new Image();img.src=item.src;}});}
  function show(index){if(!visible.length)return;active=(index+visible.length)%visible.length;const item=visible[active],box=ensureLightbox(),wasOpen=box.classList.contains('open');if(!wasOpen)lastFocus=document.activeElement;const image=$('[data-gallery-image]',box);image.src=item.src;image.alt=item.title;$('[data-gallery-title]',box).textContent=item.title;$('[data-gallery-type]',box).textContent=item.type;$('[data-gallery-caption]',box).textContent=item.caption;$('[data-gallery-count]',box).textContent=`${active+1} / ${visible.length}`;const open=$('[data-gallery-open-record]',box);open.hidden=!item.route;open.dataset.route=item.route||'';box.classList.toggle('single',visible.length<2);box.classList.add('open');box.setAttribute('aria-hidden','false');document.body.classList.add('di-gallery-lock');if(!wasOpen)$('[data-gallery-close]',box).focus();preload(active);}
  function close(){const box=$('#diGalleryLightbox');if(!box||!box.classList.contains('open'))return;box.classList.remove('open');box.setAttribute('aria-hidden','true');document.body.classList.remove('di-gallery-lock');if(lastFocus?.focus)lastFocus.focus();lastFocus=null;}
  function move(delta){if(visible.length>1)show(active+delta);}
  function openRecord(){const box=$('#diGalleryLightbox'),route=$('[data-gallery-open-record]',box)?.dataset.route;if(!route)return;close();location.hash=`#/${route}`;}
  function mount(root=document){page=$('.di-gallery-page',root);if(!page)return;cards=$$('[data-gallery-item]',page);currentFilter='all';query='';cards.forEach(card=>{const image=$('img',card);if(image){image.addEventListener('error',()=>markBroken(card),{once:true});if(image.complete&&image.naturalWidth===0)markBroken(card);}card.addEventListener('click',()=>{if(card.dataset.galleryBroken==='true')return;refreshVisible();const idx=visible.findIndex(item=>item.card===card);if(idx>=0)show(idx);});});$$('[data-gallery-filter]',page).forEach(btn=>btn.addEventListener('click',()=>applyFilter(btn.dataset.galleryFilter)));const search=$('[data-gallery-search]',page);if(search)search.addEventListener('input',()=>{query=search.value;applyFilters();});refreshFilterAvailability();applyFilters();}
  document.addEventListener('keydown',e=>{const box=$('#diGalleryLightbox');if(!box?.classList.contains('open'))return;if(e.key==='Escape')close();else if(e.key==='ArrowLeft')move(-1);else if(e.key==='ArrowRight')move(1);else if(e.key==='Tab'){const focusable=$$('button:not([hidden])',box);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
  window.DI_GALLERY={mount,close};
})();
